name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: echo Running unit tests!
      - name: Building
        run: |
          echo Building artifacts!
          sleep 5s

  deploy-qa:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v3
      - name: Deploying to Staging environment
        run: |
          echo Code was successfully deployed to STG!
          sleep 10s
      - name: Unit Testing
        run: |
          echo Running Unit tests
          sleep 5s
          
  auto-tests:
    needs: [deploy-qa]
    uses: alekxaguilar/ta-ci-web-taf/.github/workflows/auto-release.yml@main

  cleanup:
    needs: [auto-tests] 
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v3
      - name: Deploying to Staging environment
        run: |
          echo Code was successfully deployed to STG!
          sleep 5s          
