# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      auto-release-tests:
        description: "Automation Release Tests"
        required: true
        default: 'auto-release-tests'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: echo Running unit tests!
      - name: Building
        run: |
          echo Building artifacts!
          sleep 10s

  Deploy:    
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Deploying to Staging environment
        run: |
          echo Code was successfully deployed to STG!
          sleep 10s

  Tests:
    needs: [Deploy]
    uses: alekxaguilar/ta-ci-web-taf/.github/workflows/auto-release.yml@main

  Cleanup:
    needs: [Tests] 
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v3
      - name: Deploying to Staging environment
        run: |
          echo Code was successfully deployed to STG!
          sleep 10s          
